server.port=9098
spring.datasource.url=jdbc:postgresql://localhost:5432/test_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
crypto.secret.key=lUchbov1szm3LqZkngqDG4ey3B9sXOblC4hAaYA6NiE=
project.poster=poster/
base.url=http://localhost:9098